### ISSUE TITLE
Create new build

### ISSUE THREAD

**Issue by ruudk** [andyrbell/mountebank#2]
Could you please trigger a new build for https://github.com/bbyars/mountebank/releases/tag/v1.13.0?

🙏 Thanks!

**Comment by andyrbell** [comment]
Thanks for the contribution!

The version of node you've used (6.11.5) does not exist in the apk repository for alpine:3.5.

In alpine:3.6 there is a later version, 6.10.3-r1, but still no 6.11.x. Also, for 6.10.3-r1 it looks like node and npm have been split into separate packages so there is an extra `apk add` required for nodejs-npm.

The following worked for me:

```
FROM alpine:3.6

EXPOSE 2525

CMD ["mb"]

ENV NODE_VERSION=6.10.3-r1

RUN apk update \
 && apk add --no-cache nodejs=${NODE_VERSION} \
 && apk add --no-cache nodejs-npm=${NODE_VERSION}

ENV MOUNTEBANK_VERSION=1.13.0

RUN npm install -g mountebank@${MOUNTEBANK_VERSION} --production \
 && npm cache clean \
 && rm -rf /tmp/npm*

```

Do you want to update your PR with these changes so I can merge it? Thanks.

**Comment by ruudk** [comment]
Sorry, my bad! It's changed now :)
