### ISSUE TITLE
Unsure how to use docker run --net=host

### ISSUE THREAD

**Issue by slotaj** [andyrbell/mountebank#5]
I run this command and I get an output for a hash. I would expect this command to run the image instead. Any insight would be greatly appreciated, thank you!

**Comment by andyrbell** [comment]
The container should be running in the background.

`docker run --net=host -d andyrbell/mountebank`

The `-d` flag in the above command runs the docker container in [detached mode](https://docs.docker.com/engine/reference/run/#detached-vs-foreground), which will print the id of the container that has just been started.

`docker ps` will show the running containers, which should include the container id that was printed.

For this particular container, you should be able to go to http://localhost:2525 to see the Mountebank UI.

**Comment by slotaj** [comment]
Thank you for the quick response! 

It seems that the issue is I am not seeing anything at http://localhost:2525, it works however when I run the first commmand on the read me

I run ```docker run --net=host andyrbell/mountebank```

and get 

```info: [mb:2525] mountebank v2.0.0 now taking orders - point your browser to http://localhost:2525/ for help```

But then I am unable to see anything at http://localhost:2525

**Comment by andyrbell** [comment]
Depending on your platform (mac, windows, linux), you might need to use a different address e.g. http://192.168.99.100:2525. If using docker-machine, running `docker-machine ip` will give you the correct ip address to use.

As a test try:
`docker run --rm -d --network host --name my_nginx nginx`
and browse to http://localhost:80

If you don't get the nginx welcome page then I would suggest having a look at the [https://docs.docker.com/docker-for-windows/](Docker for Windows) or [https://docs.docker.com/docker-for-mac/](Docker for Mac) Getting Started guide to troubleshoot your network problem.
